# Generated by Django 2.0.5 on 2018-05-31 05:56

import cats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_auto_20180530_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, upload_to=cats.models.user_directory_path),
        ),
    ]
