# Generated by Django 2.0.5 on 2018-05-31 09:14

import cats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0005_post_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=cats.models.user_directory_path),
        ),
    ]
