# Generated by Django 2.0.5 on 2018-05-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0006_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default/profile/default-cat.jpeg', upload_to='profile/'),
        ),
    ]
