# Generated by Django 2.0.5 on 2018-05-31 11:40

import cats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0007_auto_20180531_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(upload_to=cats.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default/profile/default-cat.jpeg', upload_to='profile/'),
        ),
    ]
