# Generated by Django 2.0.5 on 2018-05-31 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0009_auto_20180531_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='relationships',
            new_name='relationship',
        ),
    ]
