# Generated by Django 2.0.5 on 2018-05-31 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0010_auto_20180531_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='relationship',
            new_name='relationships',
        ),
    ]
