# Generated by Django 2.0.5 on 2018-06-06 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0014_auto_20180606_0253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='profile',
            new_name='user',
        ),
    ]
