# Generated by Django 2.0.5 on 2018-06-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassword',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
